### ISSUE TITLE
[Request] Disabling Timestamps

### ISSUE THREAD

**Issue by cyberhicham** [laracademy/generators#13]
Hello,

The usecase for me with that package is when manipulating other databases (not laravel based ones) so I'd be happy to have this : 

```
    /**
     * Disabling Auto Timestamps.
     *
     * @var boolean
     */
    public $timestamps = false;
```

I'll try to make a PR when I got some spare time :)

**Comment by michael-mcmullen** [comment]
Closed by PR #41
