### ISSUE TITLE
When a table name is a sql keyword, the model is not generated

### ISSUE THREAD

**Issue by mitralone** [laracademy/generators#28]
When the table name is groups, the command simply throws out a SQL error. 

Here is the error:

Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups' at line 1")

**Comment by michael-mcmullen** [comment]
This has been fixed in the latest release
