### ISSUE TITLE
'describe' error during generation

### ISSUE THREAD

**Issue by NVV-WebManager** [laracademy/generators#29]
Is this expected to be compatible with a sqlsrv connection?

I'm using SQL Server as my primary database and receive the following error when trying to run a generate:modelfromtable command...

PDOException::("SQLSTATE[HY000]: General error: 20018 Could not find stored procedure 'describe'. [20018]

**Comment by michael-mcmullen** [comment]
This is because the method that is checking what the table is made up of, relates to a MySQL type of database. I would need to do some testing for a SQL Server setup (https://stackoverflow.com/questions/319354/what-is-the-equivalent-of-describe-table-in-sql-server)

**Comment by NVV-WebManager** [comment]
Understood.  I'd simply suggest in that case that you add to the requirements that a mysql connection/database is required for this package.  Thanks for the prompt reply!

**Comment by michael-mcmullen** [comment]
Added MySQL into readme
