### ISSUE TITLE
Call to undefined function Laracademy\Generators\Commands\studly_case()

### ISSUE THREAD

**Issue by smskin** [laracademy/generators#31]
PHP 7.3.4
Laravel: 6.2

Error when calling: 
 Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function Laracademy\Generators\Commands\studly_case() at /var/www/html/vendor/laracademy/generators/src/Commands/ModelFromTableCommand.php:103
![image](https://user-images.githubusercontent.com/3227797/66471934-dfa98900-ea94-11e9-96da-b66008c0ff56.png)

**Comment by michael-mcmullen** [comment]
What version of the package was pulled in? I released an update 2.0 for Laravel 6+

**Comment by wjdrnrdlekt** [comment]
@tutelagesystems  I also have same issue.
When i run php arisan `php artisan  generate:modelfromtable --all`
I got same error.

My laravel version is 6.0.1
Installed  laracademy/generators version is "^1.5"

If laravel 6.0 needs laracademy/generators 2.0.
How can i install?

Even if i try like below. i got error
![image](https://user-images.githubusercontent.com/17159184/66695786-64e4a600-ed00-11e9-8ccc-739061924e76.png)

**Comment by uintaam** [comment]
Doesn't look like 2.0 was ever tagged.

To get this working for now you can run this commend
`composer require laracademy/generators dev-master#03251ba --dev`

**Comment by michael-mcmullen** [comment]
Interesting.. Let me follow packagist new way to get methods out. I will close this once i see it has been updated on packagist.

**Comment by michael-mcmullen** [comment]
Ok, I have gone through Packagist / Github's new integrations to get the 2.0 package up (and have it automatically update).

Sorry for the troubles
