### ISSUE TITLE
laracademy/generators 2.0 empty namespace

### ISSUE THREAD

**Issue by wjdrnrdlekt** [laracademy/generators#33]
Hello. 

I am using laravel 6.1.0 & laracademy/generators 2.0

This command is not problem.
![image](https://user-images.githubusercontent.com/17159184/67137709-7e43a000-f274-11e9-90e2-a718977b713a.png)

But when i open model by made generator, i could see it.
![image](https://user-images.githubusercontent.com/17159184/67137716-9b786e80-f274-11e9-822d-d9886cb8759e.png)

There is empty after namespace. Sure, this makes error.
If i add App after namespace like this. There is no error.

`namespace  App;`

**Comment by Faks** [comment]
--namespace App

add in the argument list and issue will be fixed.
