### ISSUE TITLE
Error Class 'Str' not found on  laravel 6.1

### ISSUE THREAD

**Issue by goldgeer** [laracademy/generators#34]
when i run "php artisan generate:modelfromtable --all" in laravel 6.1. 
I found error  "Class 'Str' not found".

Starting Model Generate Command

   Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Str' not found

  at /var/www/html/lava2/vendor/laracademy/generators/src/Commands/ModelFromTableCommand.php:290
    286|         // folder
    287|         // first check for namespace
    288|         if(! $this->option('namespace')) {
    289|             // set the namespace to the folder
  > 290|             $this->options['namespace'] = Str::studly($this->option('folder'));
    291|         } else {
    292|             // default namespace
    293|             $this->options['namespace'] = ($this->option('namespace')) ? str_replace('app', 'App', $this->option('namespace')) : 'App';
    294|             // remove trailing slash if exists

  Exception trace:

  1   Laracademy\Generators\Commands\ModelFromTableCommand::getOptions()
      /var/www/html/lava2/vendor/laracademy/generators/src/Commands/ModelFromTableCommand.php:71

  2   Laracademy\Generators\Commands\ModelFromTableCommand::handle()
      /var/www/html/lava2/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  Please use the argument -v to see more details.
![image](https://user-images.githubusercontent.com/21437330/68571226-1b20e400-0495-11ea-972c-0c251893e6c3.png)

**Comment by michael-mcmullen** [comment]
Can you perform a

```
php artisan
```

And tell me the specific Laravel version? Eg: 

![image](https://user-images.githubusercontent.com/811123/68821411-46a1fb00-065c-11ea-900f-26fc5e03cdce.png)

**Comment by goldgeer** [comment]
Laravel Framework 6.1.0 

laravel + permitsion from this git
https://github.com/LaravelDaily/laravel-roles-permissions-manager

**Comment by michael-mcmullen** [comment]
It has been updated for laravel 6, just need to grab the 2.x release
