### ISSUE TITLE
unable to set which database use as default database name is appended automaticaly,

### ISSUE THREAD

**Issue by scramatte** [laracademy/generators#39]
Hello,

I've got one mysql user that can access various databases on the same server
I'm trying toe generate model but it. doesn't works. because your script append the default database name.

```
php artisan generate:modelfromtable --table=dbx.users--folder=app\Models

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'websockets.dbx.users' doesn't exist
```

¿Can you fix it ?

Regards

**Comment by michael-mcmullen** [comment]
Have you tried the `connection` option?

**Comment by scramatte** [comment]
thank you to reply.  I've got only one connection
I've same user  but different schema (database) on the same server :  db1.table,  db2.table, dbx.table...

**Comment by scramatte** [comment]
I believe that I found the problem. 
In your code you do  `DB::raw("describe ``{$tableName}``")`

The problem is in  quotes chars around table name. Quick fix is removed them  but  good fix, will be parse table name and add quotes. For example  instead of   `crm.contacts`   it should be  `crm` .`contacts`

Moreover  Schema::getColumnListing neither works  that is much more  problematic...

**Comment by scramatte** [comment]
Here a quick  and  dirty fix but as "describe" , it will works only with MySQL

```
public function getSchema($tableName)
{
    $this->doComment('Retrieving table definition for: '.$tableName);

     if (strpos($tableName,'.')>1) {
        list($schema, $tableName) = explode('.',$tableName);
     } else {
        $schema = DB::connection()->getDatabaseName();
     }

     $raw = DB::raw("select column_name as `column_name` from information_schema.columns where table_schema = '{$schema}' and table_name = '{$tableName}'");
 
    if (strlen($this->options['connection']) <= 0) {
        $result = DB::select($raw); 
    } else {
        return DB::connection($this->options['connection'])->select($raw);
    }
    return collect($result)->pluck('column_name');
}
```
