### ISSUE TITLE
[Request]Creating folders when they don't exist

### ISSUE THREAD

**Issue by cyberhicham** [laracademy/generators#4]
That package is great for what I'm trying to do (Data migration between 2 external Databases)
It generates all the models from the 2 dbs, maybe it can create the folder if it does not exist and we specify it with the --folder flag ?

**Comment by laracademy** [comment]
It will now check the folder to see if it exists and if it doesn't then it will try to create it. So you will need to ensure that you as the user running the command have the correct permissions to make the folder.

**Comment by cyberhicham** [comment]
All is good, thx!
