### ISSUE TITLE
Command Dosent recognise the --all command

### ISSUE THREAD

**Issue by ax3cubed** [laracademy/generators#44]
I entered this command
php artisan generate:modelfromtable --all --folder=app/Models
Starting Model Generate Command
No --table specified or --all

Yet it didn't find the --all command

**Comment by johnneijzen** [comment]
you made the same mistake as me #42 just do --all=true and I did submit pull request #43 to lower confusion 

do if want generates all models use this command:
php artisan generate:modelfromtable --all=true

**Comment by daverogers** [comment]
Sorry about that, I hadn't had time to update the docs. Thanks @johnneijzen!
