### ISSUE TITLE
Laravel 8 make default namespace App\Models instead of App

### ISSUE THREAD

**Issue by johnneijzen** [laracademy/generators#45]
it annoying having to this every time I make a new model

**Comment by michael-mcmullen** [comment]
Thanks to @danrovito for fixing it so fast, I will push up a new version

**Comment by daverogers** [comment]
In the future, you could use a config as well by copying [this file](https://github.com/laracademy/generators/blob/master/config/modelfromtable.php) into your config folder and setting 'namespace' to whatever you need it to be. This is something that needs to be documented in this repo but overall is a general practice in a lot of Laravel projects and on new installs this config file _should_ show up in your config folder automatically.
