### ISSUE TITLE
Generate an Uppercase first letter, singular name in Model from lower case plural name of a table.

### ISSUE THREAD

**Issue by Redcode456123** [laracademy/generators#47]
Hi all,

1) I am beginner learner of Laravel. I tried to generate a model class from an existing table in mysql.
The generator generates a Model with uppercase but not singular! .I tried to rename the file in IDE but it throws an error. My syntax is :php artisan generate:modelfromtable --table=jobs.
2) what about if I want to get "Category" Model class if my table name is"categories" ?

Thanks for help.

**Comment by daverogers** [comment]
yeah, try adding `--singular=true`

**Comment by Redcode456123** [comment]
Thanks daverogers, yes that works,
for future users:
--in vendor/laracademy/generators/config/modelfromtable.php , modify 'singular'=>true, (Line 31), and save it.

**Comment by daverogers** [comment]
I wouldn't update the vendor file directly, but instead copy that config file to your project's local config directory if it's not there already, then update that value :)
