### ISSUE TITLE
[Bug] specifying global namespace

### ISSUE THREAD

**Issue by cyberhicham** [laracademy/generators#5]
All the models are generated with the default 'App' namespace, even if the app has another global namespace 'artisan app:name'

**Comment by laracademy** [comment]
Try using `--namespace=Your\namespace\here`

I haven't documented it, but it is in the code

**Comment by cyberhicham** [comment]
Sure it is in the code ?
![screenshot-199](https://cloud.githubusercontent.com/assets/10002527/18280163/af689a18-7447-11e6-9a52-b677101a9963.png)

**Comment by laracademy** [comment]
Definitely in the latest release 1.3.1, sorry about that :D

**Comment by cyberhicham** [comment]
All is good, thx !
