### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by breakdom** [laracademy/generators#53]
Hi I have installed the library but I am getting this error:   

syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'
at vendor/laracademy/generators/src/Commands/ModelFromTableCommand.php:316

LINE 316 : 

$padding = array_reduce(array_keys($types), fn($carry, $x) => max($carry, strlen($x)), 0) + 15;

**Comment by breakdom** [comment]
RESOLVED : I need to install php 7.4.

**Comment by zacglenn** [comment]
@breakdom check out #57 and the PR related; this removes the need to install php 7.4; hope you may find this helpful
