### ISSUE TITLE
Arrow function usage breaks compatibility for PHP Version 7.3.33 users

### ISSUE THREAD

**Issue by zacglenn** [laracademy/generators#57]
https://github.com/laracademy/generators/blob/a06e98d106afcf5f0f55860975a91c74cf4633ce/src/Commands/ModelFromTableCommand.php#L212

This single instance use of php 7.4's arrow function in the aforementioned line breaks compatibility for php version 7.3.33 users.

This is resolved by changing the aforementioned line to the following line:
`$padding = array_reduce(array_keys($types), function ($carry, $x) { return max($carry, strlen($x)); }, 0) + 15;`

Replacing `fn($carry, $x) => max($carry, strlen($x))` with `function ($carry, $x) { return max($carry, strlen($x)); }` restores functionality.

**Comment by daverogers** [comment]
7.3 is [EOL](https://www.php.net/supported-versions.php)

**Comment by zacglenn** [comment]
@daverogers ah wasn't aware; thank you for the link; will move forward accordingly; will close this as well
