### ISSUE TITLE
unexpected '=>' (T_DOUBLE_ARROW), expecting ')' fn

### ISSUE THREAD

**Issue by AlefMac** [laracademy/generators#59]
solve by going to the file directory and change the fn to this here:

$padding = array_reduce(array_keys($types), **function($carry, $x){ return max($carry, strlen($x)); }**, 0) + 15;

**Comment by daverogers** [comment]
You're likely using a pretty old version of PHP, which is [no longer supported by PHP themselves](https://www.php.net/supported-versions.php).
