### ISSUE TITLE
[Request] Specifying the database connection for the generated models

### ISSUE THREAD

**Issue by cyberhicham** [laracademy/generators#6]

**Comment by laracademy** [comment]
have you tried using the flag `--connection=someConnectionInYourDBConf`

**Comment by cyberhicham** [comment]
I looked in your model stub, what I mean is in the model if the protected connection var can be set with the --connection flag it will make sense, like 

`````` /**
     * The database connection used by the model.
     *
     * @var string
     */
    protected $connection = 'someConnectionInYourDBConf';```
``````

**Comment by laracademy** [comment]
You know what I do have a version that had that in it; give me a little bit and i'll commit it all

**Comment by cyberhicham** [comment]
Sure, no rush :)

**Comment by laracademy** [comment]
Give it a try

**Comment by cyberhicham** [comment]
That works!
I couldn't get the package updated by composer update, had to change the model.stub manually to reflect your changes

**Comment by laracademy** [comment]
Sorry, I didn't make a release for it.

Everything has been packaged in the new release 1.3.1 so composer will grab it correctly.

**Comment by cyberhicham** [comment]
All is good, thx!
