### ISSUE TITLE
Duplicate Columns and unnecessary models generating

### ISSUE THREAD

**Issue by hassaanih** [laracademy/generators#60]
Hi Everyone,

I have a project where I have used MySQL as database. The problem I am getting is that I am getting system oriented model such as AccessLogs. The models that are generated also has many repetitive column. I am pasting the image 
![image](https://user-images.githubusercontent.com/39552896/160842153-ab332d85-1d66-4ff0-9398-edb76ee926f0.png)

also 

![image](https://user-images.githubusercontent.com/39552896/160842282-6e1f41a9-569c-4b4b-8fee-1258276a16d2.png)

**Comment by daverogers** [comment]
Ah, looks like MySQL 8 includes a schema called "performance_schema", which needs to get added to the [schema filter](https://github.com/laracademy/generators/blob/master/src/Commands/ModelFromTableCommand.php#L362-L365).

For now, if you include "schema" in the CLI or in your configuration file, it won't have to resort to trying to find it which would fix your issue in the meantime.

As far as the repetitive column, could you include the create statement for the table it's having that issue with? (you can prune the non-relevant stuff, mostly interested in whatever coupon column(s) are in there).

**Comment by hassaanih** [comment]
Thanks for the reply the issue appears to be fixed kudos to you my friend your a life saver..
