### ISSUE TITLE
Satisfied, but still room to improvement

### ISSUE THREAD

**Issue by TNChalise** [laracademy/generators#7]
Currently, I am satisfied with the approach. But we are using smarter IDEs for development, and I need still to add model properties to the doc block for the type hinting while assigning or accessing model attributes as:

``` php
     @property string    $created_at
     @property Date      $updated_at
     @property DateTime  $deleted_at
```

with in the model class. If it is possible and easy to go, please add this feature with in class doc block.
Still searching for fair model generation modules as Yii has.
PS: I am using PHPStrom.

**Comment by michael-mcmullen** [comment]
Closed by PR #41
